services:

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/config-repo:ro
    container_name: config-server
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/8888"]
      interval: 10s
      timeout: 5s
      retries: 10

  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    container_name: discovery-server

  gateway-service:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_started
    container_name: gateway-service

  book-service:
    build: ./book-service
    ports:
      - "8081:8082"
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_started
      kafka:
        condition: service_started
    container_name: book-service

  auth-service:
    build: ./auth-service
    ports:
      - "8082:8081"
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_started
    container_name: auth-service

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    container_name: zookeeper

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    container_name: kafka

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    container_name: grafana

  vendas-service:
    build: ./vendas-service
    ports:
      - "8083:8083"
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_started
      book-service:
        condition: service_started
      kafka:
        condition: service_started
    container_name: vendas-service
