spring.application.name=api-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=api-docs-auth
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth-api-docs

spring.cloud.gateway.routes[1].id=api-docs-book
spring.cloud.gateway.routes[1].uri=lb://BOOK-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/livros-api-docs

spring.cloud.gateway.routes[2].id=api-docs-vendas
spring.cloud.gateway.routes[2].uri=lb://VENDAS-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/vendas-api-docs

spring.cloud.gateway.routes[3].id=auth-service
spring.cloud.gateway.routes[3].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[4].id=book-service
spring.cloud.gateway.routes[4].uri=lb://BOOK-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/livros/**

spring.cloud.gateway.routes[5].id=vendas-service
spring.cloud.gateway.routes[5].uri=lb://VENDAS-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/vendas/**

springdoc.swagger-ui.urls[0].name=auth
springdoc.swagger-ui.urls[0].url=/auth-api-docs
springdoc.swagger-ui.urls[1].name=books
springdoc.swagger-ui.urls[1].url=/livros-api-docs
springdoc.swagger-ui.urls[2].name=vendas
springdoc.swagger-ui.urls[2].url=/vendas-api-docs
